/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.media-edge.jsonc --include-runtime=false --env-interface=MediaEdgeEnv types/media-edge-env.d.ts` (hash: d64f97ef15a852ff9c7f8fa3b6f168e0)
interface __BaseEnv_MediaEdgeEnv {
	MEDIA: R2Bucket;
	HOME: Fetcher /* psr-home-video-guard */;
	ROADSHOW: Fetcher /* psr-roadshow-dates */;
	ROADSHOW_BROCHURE: Fetcher /* psr-roadshow-brochure */;
	ROADSHOW_PLAN: Fetcher /* psr-roadshow-plan */;
	ROADSHOW_NURTURE: Fetcher /* psr-roadshow-nurture */;
	PROJECTS: Fetcher /* psr-projects-clean */;
	SHELL: Fetcher /* psr-shell-events */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../worker/media-edge");
	}
	interface Env extends __BaseEnv_MediaEdgeEnv {}
}
interface MediaEdgeEnv extends __BaseEnv_MediaEdgeEnv {}
